apiVersion: recon.bewley.net/v1alpha1
kind: OvnRecon
metadata:
  labels:
    app.kubernetes.io/name: ovn-recon
    app.kubernetes.io/instance: ovn-recon
    app.kubernetes.io/managed-by: kustomize
  name: ovn-recon
spec:
  targetNamespace: ovn-recon
  image:
    repository: quay.io/dbewley/ovn-recon
    tag: v0.1.0
    pullPolicy: Always
  consolePlugin:
    displayName: "OVN Recon"
    enabled: true
