apiVersion: recon.bewley.net/v1beta1
kind: OvnRecon
metadata:
  name: ovn-recon
spec:
  targetNamespace: ovn-recon
  consolePlugin:
    displayName: OVN Recon
    enabled: true
    image:
      repository: quay.io/dbewley/ovn-recon
  collector:
    enabled: false
    image:
      repository: quay.io/dbewley/ovn-collector
    probeNamespaces:
      - openshift-ovn-kubernetes
      - openshift-frr-k8s
