apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: guifreelife-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/dbewley/guifreelife-operator-index:v4.20
  displayName: Guifreelife Operators
  publisher: GUIFreeLife
  updateStrategy:
    registryPoll:
      interval: 1h
