apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: bewley-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/dbewley/bewley-operator-catalog:v4.20
  displayName: Bewley Operators
  publisher: Dale Bewley
  updateStrategy:
    registryPoll:
      interval: 1h
