apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: ovn-recon
spec:
  displayName: "OVN Recon"
  backend:
    type: Service
    service:
      basePath: /
      name: ovn-recon
      namespace: ovn-recon
      port: 9443