apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovn-recon
  labels:
    app: ovn-recon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovn-recon
  template:
    metadata:
      labels:
        app: ovn-recon
    spec:
      # imagePullSecrets:
      #   - name: quay-pullsecret
      containers:
        - name: ovn-recon
          image: quay.io/dbewley/ovn-recon:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
