apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-console-plugin
  labels:
    app: ocp-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-console-plugin
  template:
    metadata:
      labels:
        app: ocp-console-plugin
    spec:
      # imagePullSecrets:
      #   - name: quay-pullsecret
      containers:
        - name: ocp-console-plugin
          image: quay.io/dbewley/ocp-console-plugin:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
