apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-pullsecret
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pull-secret/QUAY/json
      metadataPolicy: None
    secretKey: pullSecret

  refreshInterval: 0s
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-pullsecret
    template:
      data:
        .dockerconfigjson: '{{ .pullSecret }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata: {}