---
apiVersion: v1
kind: Service
metadata:
  name: ocp-console-plugin
  labels:
    app: ocp-console-plugin
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  selector:
    app: ocp-console-plugin
  ports:
    - name: https
      port: 9443
      targetPort: 9443
      protocol: TCP
  type: ClusterIP
