apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ovn-recon-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ovn-recon-operator
  source: bewley-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ovn-recon-operator.v0.0.5
