apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovn-recon.fullname" . }}
  labels:
    {{- include "ovn-recon.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin
    app.kubernetes.io/part-of: openshift-console-plugin
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "ovn-recon.selectorLabels" . | nindent 4 }}
