name: Collector Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'collector/**'
      - '.github/workflows/collector-release.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'collector/**'
      - '.github/workflows/collector-release.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Test
        run: |
          cd collector
          make test

      - name: Build
        run: |
          cd collector
          make build

      - name: Set Release Metadata
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          if [[ "$VERSION" == *"-"* ]]; then
            EXPIRY_TIME=$(date -d "30 days" +%s)
            echo "EXPIRY_LABEL=--label quay.expires-at=$EXPIRY_TIME" >> $GITHUB_ENV
          else
            echo "EXPIRY_LABEL=" >> $GITHUB_ENV
          fi

      - name: Build Collector Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "Building version $VERSION with $EXPIRY_LABEL"
          docker build $EXPIRY_LABEL -t quay.io/dbewley/ovn-collector:$VERSION collector
          if [[ "$VERSION" != *"-"* ]]; then
            docker tag quay.io/dbewley/ovn-collector:$VERSION quay.io/dbewley/ovn-collector:latest
          fi

      - name: Login to Quay.io
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push Collector Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push quay.io/dbewley/ovn-collector:$VERSION
          if [[ "$VERSION" != *"-"* ]]; then
            docker push quay.io/dbewley/ovn-collector:latest
          fi
