name: Operator Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'operator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'operator/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: |
        cd operator
        make build

    - name: Test
      run: |
        cd operator
        make test

    - name: Build Operator Image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cd operator
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Building version $VERSION"
        docker build -t quay.io/dbewley/ovn-recon-operator:$VERSION .
        if [[ "$VERSION" != *"-"* ]]; then
          docker tag quay.io/dbewley/ovn-recon-operator:$VERSION quay.io/dbewley/ovn-recon-operator:latest
        fi

    - name: Login to Quay.io
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Push Operator Image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        docker push quay.io/dbewley/ovn-recon-operator:$VERSION
        if [[ "$VERSION" != *"-"* ]]; then
          docker push quay.io/dbewley/ovn-recon-operator:latest
        fi
